### ISSUE TITLE
Retrieve a subset dataframe after qgrid filtering

### ISSUE THREAD

**Issue by rodolfo-flores-tierconnect-com** [quantopian/qgrid#117]
- Jupyter Notebook (Anaconda distribution)
- Pandas 0.20.1
- Qgrid 0.3.3

Is there an option to retrieve a filtered dataset as a new dataframe?, i tried this but when I get a dataframe back, it's still show me all rows.

Note that the column BroadPhaseofFlight is filtered only for "APPROACH" values
`from IPython.display import display`
`grid = qgrid.QGridWidget(df=test)`
`display(grid)`
![2017-06-30 16_47_13-mongo](https://user-images.githubusercontent.com/18538611/27743400-cf4cb408-5db3-11e7-89a8-57430cdbd083.png)

`display(grid.df)`
![2017-06-30 16_49_23-mongo](https://user-images.githubusercontent.com/18538611/27743501-1d7072a0-5db4-11e7-970f-13a13c5da629.png)

Thanks a lot for your help

**Comment by TimShawver** [comment]
Thanks for the feedback.  This issue is already logged here: https://github.com/quantopian/qgrid/issues/87 so I'm going to close this issue.

I'm currently working on a project which moves the sorting and filtering logic to the notebook server (currently it's done in javascript in the browser), and this problem will get solved as part of that project.  I'll close that other issue (https://github.com/quantopian/qgrid/issues/87) once I finish that project, so if you subscribe to notifs on that issue, you should be notified when this is fixed.
