### ISSUE TITLE
Horizontal Scrolling in QGrid

### ISSUE THREAD

**Issue by JohnOmernik** [quantopian/qgrid#118]
I've noticed that my gestures on my mac for horizontal scrolling do not seem to work with qgrid.  For example, if I have a data frame with say 20 columns and try to display with the standard display in iPython notebooks, if I hover over the grid with my mouse and do a two finger side to side swipe I can scroll horizontally to see all columns in qgrid, it doesn't register that, I can arrow over, but now scroll with the mouse... have other seen this too?

**Comment by TimShawver** [comment]
Hmm weird, I wasn't able to reproduce this.  I'm curious to hear if anyone else has this issue.  I'm on Sierra.

**Comment by rodolfo-flores-tierconnect-com** [comment]
I have a similar problem in export-mode with horizontal scrolling, it disappears when vertical scrolling is not needed, it means when rows height is less than the div container height

Example 1 (100 Rows).- Horizontal Scrolling looks and works good
![image](https://user-images.githubusercontent.com/18538611/29336861-482007a2-81dd-11e7-8cf3-fa815d18da0b.png)


Example 2 (3 Rows).- When Vertical Scrolling is not needed, Horizontal Scrolling disappears too, and I can't go to the right to see the other columns
![image](https://user-images.githubusercontent.com/18538611/29336912-74e6124a-81dd-11e7-8442-a6d5e74a9c4a.png)

qgrid 0.3.3

**Comment by TimShawver** [comment]
I think this might be fixed in the new qgrid 1.0 beta...I fixed a bunch of scrollbar issues and I think this may have been one of them. 

See the installation instructions on the [updated readme page](https://github.com/quantopian/qgrid#installation) to try out qgrid 1.0.

I'm actually not 100% sure it's fixed though so please let me know if you're able to try it out.
