### ISSUE TITLE
Option to consider - Pop out to new Window

### ISSUE THREAD

**Issue by JohnOmernik** [quantopian/qgrid#120]
Having the qgrid is great, it's very functional, consider an option to add a "pop-out" button, where if the user clicks on the button, it takes the qgrid and opens a new window with the data in it. (with another Qgrid). This new window would not be constrained by the iPython notebook display size, and could be resized to work with whatever screen real-estate the user may have.

**Comment by TimShawver** [comment]
Thanks, good idea.  Qgrid should be able to work in Jupyterlab once I merge the project I'm currently working on, and in Jupyterlab you can do cool stuff with widgets like drag them onto a separate tab which appears next to your notebook.  I'm hoping that functionality may satisfy this need (haven't actually gotten qgrid working in Jupyterlab yet) but if not I could look into adding a "pop-out" button as you describe.

**Comment by TimShawver** [comment]
I was inspired by your idea and added a "full screen" button in the qgrid 1.0 beta.  It's not quite what you're asking for because it doesn't open a separate window, but it serves a similar purpose.  I'm going to close this because I don't expect to do work on this beyond adding the full screen button.

The grid inline with the notebook:
![screen shot 2017-10-16 at 11 27 40 am](https://user-images.githubusercontent.com/5055866/31620557-8c55bc1a-b265-11e7-8e0c-b3b36cfbd118.png)

Full screen mode:
![screen shot 2017-10-16 at 11 27 18 am](https://user-images.githubusercontent.com/5055866/31620655-d15a3b24-b265-11e7-8372-e7164d3eeaf0.png)
