### ISSUE TITLE
Notebook Example 1 - Yahoo Demo is Broken

### ISSUE THREAD

**Issue by brycepg** [quantopian/qgrid#124]
http://ichart.finance.yahoo.com/ no longer exists
which causes Example 1 in the demo to break
I know this is an issue for pandas_datareader however, it may be a good idea to remove this example.

**Comment by brycepg** [comment]
Here's the issue for pandas-datareader: https://github.com/pydata/pandas-datareader/issues/356

**Comment by TimShawver** [comment]
Thanks, yea good call.

**Comment by TimShawver** [comment]
I've updated the demo notebook we use for qgrid 1.0.  It still contains a demo that uses yahoo pricing data, but that appears to be working most of the time.  There is still intermittently an error with retrieving the data but I think that's OK because the error always goes away for me if I run the cell again.
