### ISSUE TITLE
Pagination feature to avoid Timeout error in Export mode

### ISSUE THREAD

**Issue by rodolfo-flores-tierconnect-com** [quantopian/qgrid#126]
I'm having timeout error when I call qgrid from Jupyter Dashboard Server, my pandas dataframe has ~30k rows and the page could not load the data. 
Qgrid has pagination option or another technique to handle this problem? I know that I can increase the timeout limit of the client, in this case in Jupyter Dashboard Server, but I think this will be a temporal fix only.

![qgrid_issue](https://user-images.githubusercontent.com/18538611/29088576-8782986a-7c47-11e7-8229-6c05310170c4.png)

 Thanks.

**Comment by TimShawver** [comment]
Hi I'm working on a branch of qgrid that will enable it to handle more rows https://github.com/quantopian/qgrid/pull/125, but it's not done yet, and also I don't think it will work with the Dashboard Server because it depends on a new version of ipywidgets that the Dashboard Server doesn't support yet (and it sounds like the Jupyter team's plan is to add some dashboard-type functionality to the jupyterlab rather than continuing the Dashboard Server project https://github.com/jupyterlab/jupyterlab/issues/1640#issuecomment-318392805).

So unfortunately I don't have a workaround for this available yet.  Long term the hope is that you'll be able to do your dashboarding in Jupyterlab, and in that context you'll be able to use the new version of qgrid that can handle much larger DataFrames.

**Comment by TimShawver** [comment]
Closing since it's a dashboards issue, and it doesn't make sense for us to support dashboards since that project is likely being replaced by jupyterlab.
