### ISSUE TITLE
get_selected_rows doesn't account for filtering/sorting

### ISSUE THREAD

**Issue by corbettjj** [quantopian/qgrid#137]
If you sort a dataframe (below I use the binder Example 1) of indexes 0-8 in descending order by index, and select the first three rows, and run get_selected_rows(), I believe intended functionality should return indexes [8,7,6]. Instead, it always returns indexes [1,2,3] when you select the first three rows regardless of how you sorted/filtered the indexes. This makes getting the actual "indexes" (rather than just positions) require an extra step, for example via: `actual_indexes = qgrid_widget.get_changed_df().index[qgrid_widget.get_selected_rows()]` Is this intended functionality?

![image](https://user-images.githubusercontent.com/6678207/31848936-b91af2c8-b608-11e7-80e3-81737234b4a7.png)

![image](https://user-images.githubusercontent.com/6678207/31849026-b4d3f4f2-b609-11e7-9489-926c24bf70be.png)

![image](https://user-images.githubusercontent.com/6678207/31849138-949b2b86-b60b-11e7-8323-b4658861bd08.png)

**Comment by TimShawver** [comment]
Interesting...yea I think it's probably more useful to return the index of the DataFrame (i.e. 8, 7, 6).  I can't think of anything that the index of the SlickGrid control (i.e. 0, 1, 2) would be useful for.  I'll try and include this in the next beta. Thanks.

**Comment by TimShawver** [comment]
@corbettjj I decided it might be better to have a new method called `get_selected_df` which returns a DataFrame that includes all of the selected rows.  This way, if you want to access some other column for the selected rows, you don't have to call `get_changed_df` yourself.

So using your example, you'd do the following to get the selected indices of the DataFrame, once I merge this change and release it:
```
actual_indices = qgrid_widget.get_selected_df().index
```
Does that sound like it will work for you? I'm thinking of leaving the `get_selected_rows` method as is for now since it's possible the way it currently works will be useful to someone.

**Comment by corbettjj** [comment]
That sounds great. I agree it's useful to also retain the functionality of the current get_selected_rows. Thanks!
