### ISSUE TITLE
qrid widgets not showing

### ISSUE THREAD

**Issue by yoni-madlan** [quantopian/qgrid#149]
Using the code from the demonstration notebook, I can't see the qgrid widget or the table at all.
I installed qgrid exactly as mentioned in the instructions, with conda.
My ipywidgets version is 7.0.5, and other ipywidgets display correctly.

**Comment by TimShawver** [comment]
Hmm I just tried on Python 3.6 and MacOS Sierra and it's working for me.  Also the [binder demo notebook](https://beta.mybinder.org/v2/gh/quantopian/qgrid-notebooks/master?filepath=index.ipynb) uses conda and that's working fine.  

Could you send the following info:
- output from `conda list`
- output from `conda info` (the first 6 lines, before `root environment:`)
- output from `jupyter nbextension list`

Thanks.

**Comment by yoni-madlan** [comment]
conda info: 
              platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.23
         python version : 3.6.3.final.0
       requests version : 2.18.4

jupyter nbextension list:

Known nbextensions:
  config dir: /home/yoni/.jupyter/nbconfig
    notebook section
      nbextensions_configurator/config_menu/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      nbpresent/js/nbpresent.min  enabled 
      - Validating: problems found:
        - require?  X nbpresent/js/nbpresent.min
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
    tree section
      nb_conda/tree  enabled 
      - Validating: OK
  config dir: /home/yoni/anaconda3/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      nbpresent/js/nbpresent.min disabled
      nb_conda/main  enabled 
      - Validating: OK
      nbextensions_configurator/config_menu/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      qgrid/extension  enabled 
      - Validating: OK
    tree section
      nb_conda/tree  enabled 
      - Validating: OK
      nbextensions_configurator/tree_tab/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main


the conda list is long, so I attached it as a file [conda_list.txt](https://github.com/quantopian/qgrid/files/1531648/conda_list.txt)

**Comment by TimShawver** [comment]
Thanks...I tried to replicate your environment to some extent but couldn't reproduce it.  
 
Are you seeing any errors in the notebook server logs or in the js console in your browser? What type of browser are you using?

If there aren't any errors in the logs, next thing I would try is creating a new conda environment and doing a fresh install of qgrid. You have lots of nbextensions installed here, including one which is meant to manage configuration of other nbextensions and has problems listed in your `jupyter nbextension list` output, so I'm suspicious about that.  So if you don't mind giving that a shot, that would tell us whether this problem is related to the specific stuff you have installed, or something more general like being OS/browser related. Thanks.

**Comment by yoni-madlan** [comment]
It didn't work both on Mozilla and Chromium. 
A fresh install did the trick.

Thanks!
