### ISSUE TITLE
QgridWidget events?

### ISSUE THREAD

**Issue by lapsya** [quantopian/qgrid#176]
Hello!

I can't seem to find any documenation on `QgridWidget` events.
There seems to be a `notify_change` method, but I'm not sure if it's even related to it.

Are there any events that signal that some cell has been changed or that a row has been selected?

Thanks!

**Comment by TimShawver** [comment]
This is not in the official API docs yet but the "change" event for the `_df` traitlet on the `QgridWidget` object will be fired whenever a cell is edited, as well as when filtering or sorting changes are made.  You can listen for this event like this:
```
def func(change):
    print(change['old'])
    print(change['new'])

qgrid_widget.observe(on_value_change, names=['_df'])
```
See the traitlets docs for more information on observing changes to traitlets: http://traitlets.readthedocs.io/en/stable/using_traitlets.html#observe

Qgrid doesn't yet have an event for row selection being changed.  That seems like something that's worth adding though.

**Comment by lapsya** [comment]
@TimShawver, thanks!
It'll be great if you ever decide to implement row selection events

**Comment by sergun** [comment]
+1 for row(s) selection event

**Comment by paulperry** [comment]
+1 for row selection event!

For example, show a table of stocks, select a row, and have some other plot (timeseries?) reflect that stock.

**Comment by TimShawver** [comment]
Cool...yea seems like there are many interesting uses for this feature and it should be easy to add, so I'll add it at some point, hopefully in the next release.

**Comment by maximkornilov** [comment]
Just in case. You already can handle row selection event. Instead of or in addition to `_df ` you can add the observer to `_selected_rows` to monitor selected rows changes. This will give the ability to react to row selection. This code works fine for me in the current version of the qGrid:
```
info_grid = qgrid.show_grid(df)

def on_row_selected(change):
    print(change)

info_grid.observe(on_row_selected, names=['_selected_rows'])
```

**Comment by TimShawver** [comment]
Cool! Thanks @maximkornilov I didn't realize that would work.

**Comment by hanangithub** [comment]
I want to change the grid header according the line that user select , is it possible ? and refresh only the header

**Comment by Robuko** [comment]
@maximkornilov that's awesome.  How did you find the accessible trait names?

**Comment by TimShawver** [comment]
You mean the header for a particular column in the grid? I think that should be doable by modifying the internal dataframes that qgrid maintains but it's not well-supported by the API yet.  You might consider doing something like using qgrid inside of a layout widget which places some sort of ipywidgets control above qgrid, which can show whatever information you want about the selected row.

As of qgrid 1.0.3 you can attach event handlers for almost any interaction that occurs in qgrid.  In the case you're interested in the relevant event would be `selection_changed`, so listening for that event would look like this:
```
def handle_selection_changed(event, qgrid_widget)
    # update the ipywidgets control above the grid
    pass

qgrid.on('selection_changed', handle_selection_changed)
``` 

See the [API docs](https://qgrid.readthedocs.io/en/latest/#qgrid.QgridWidget.on) the [readme](https://github.com/quantopian/qgrid#events-api) or the [events notebook](https://mybinder.org/v2/gh/quantopian/qgrid-notebooks/master?filepath=events.ipynb) for more information.

I'm going to close this issue now because the events API is now available and should satisfy all event handling needs.  Please let me know if it doesn't work for you for some reason though.
