### ISSUE TITLE
Error displaying widget in beta Jupyterlab (v0.31)

### ISSUE THREAD

**Issue by nickteff** [quantopian/qgrid#177]
### Environment

* Operating System: Windows 10
* Python Version: `Python 3.6.2` Anaconda
* How did you install Qgrid: `pip`
* Python packages: 
`qgrid 1.0.0`,
 `notebook 5.0.0`,
 `jupyterlab 0.31.10`
* Jupyter lab packages (if applicable):
 `@jupyter-widgets/jupyterlab-manager v0.33.2`
`qgrid v1.0.1`

### Description of Issue

Attempting to use `qgrid` within the recent beta release of `jupyterlab`.  Instead of seeing the interactive data frame, I get an error message **Error displaying widget**.  I tested creating another `ipywidgets` slider widget with success.  See the image attached below.

 
![jlab_issue](https://user-images.githubusercontent.com/8412364/36907173-8574fe48-1dfd-11e8-96b8-c14545f25b49.png)

### Reproduction Steps
```
import numpy as np
import pandas as pd
import qgrid as q

df = pd.DataFrame(np.random.random((6,6)))

w = q.show_grid(df)

w
```

**Comment by TimShawver** [comment]
If the versions you're reporting are correct, this is probably because the version of your qgrid python package (1.0.0) doesn't match the version of your qgrid jupyterlab package (1.0.1).  Those versions need to match exactly.  To get them to match you can upgrade your python package by doing:
```
pip uninstall qgrid
pip install qgrid==1.0.1
```
(I'm specifying the version explicitly even though that's the latest release, for clarity, and to prevent this comment from becoming outdated next time I release a version)

If that doesn't fix it, could you send me any errors you're seeing in the js console or in your jupyterlab logs?

**Comment by nickteff** [comment]
@TimShawver that was it.  Thank you!
