### ISSUE TITLE
No filter icon for Strings (`object`) columns in pandas dataframe

### ISSUE THREAD

**Issue by mpschr** [quantopian/qgrid#25]
Hi,

In the example at nbviewer, there are also filter icons displayed for non-numeric columns, which does not happen on my local install.

Would you know why this is the case? May it be because the the `qgrid.nbinstall()` command gives the following error: `PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter'`? It seems to work fine otherwise (and I am not sure why this nbinstall() needs to be run.

Thanks for any help!

**Comment by TimShawver** [comment]
Hmm that's pretty strange.  Sounds like that permission error could be related since nbinstall normally doesn't print any errors.  Nbinstall needs to be run to install the plugin into your jupyter notebook installation.  `pip install` qgrid only installs the python package and doesn't know anything about how you're running jupyter notebook.

Closing since this seems like an environment issue and not a qgrid problem.
