### ISSUE TITLE
Add an IPython Widget?

### ISSUE THREAD

**Issue by blink1073** [quantopian/qgrid#26]
I created a [QGrid IPython Widget](https://gist.github.com/blink1073/184601e653a0e4aace9f) (valid for IPython 3.x).  It adds the ability to edit the dataframe in-place, including adding and removing rows.  It requires no changes to the existing codebase.

Are you interested in a PR that adds this widget?  
I'm not sure what the best way to package it would be.   Perhaps a `qgrid.prepare_notebook()` that loads `qgrid_widget.js` using `IPython.display.Javascript`.  You could then expose `qgrid.QGridWidget` as well as `qgrid.edit_dataframe()`, that runs the application with the add/remove row buttons and returns the modified dataframe.

![qgrid_widget](https://cloud.githubusercontent.com/assets/2096628/9028146/3611c7e2-3934-11e5-97b0-131a3e5be2f2.gif)

**Comment by blink1073** [comment]
cc @ellisonbg @fperez @SylvainCorlay

**Comment by ssanderson** [comment]
@blink1073 this looks awesome!  Making QGrid a widget is definitely something we're interested in.  In fact, my first inclination would be to say that the widget view should be the default interaction mode.  Do you imagine use-cases where you *wouldn't* want the interactive components?  Does the widget view incur substantial performance overhead?

Could you open a PR for this?

**Comment by ssanderson** [comment]
cc @TimShawver

**Comment by llllllllll** [comment]
This is really cool!

**Comment by blink1073** [comment]
@ssanderson, it has about the same overhead, but widget outputs are not stored within the notebook file, which means you lose the ability to interact with the data in a static view.

**Comment by ssanderson** [comment]
> but widget outputs are not stored within the notebook file, 

Ah, that makes sense.  There are cases where that's desirable though: notebooks with QGrid outputs can be **much** larger than normal notebooks, because we're rendering thousands of rows of data as in-line javascript object literals.  I imagine that this could be made substantially more efficient by sending the data over a socket in a more appropriate serialization format and then doing the conversion to objects in Javascript.

w/r/t preserving the outputs, I wonder if what this wants is something like an **Embed** or a **Render** button that renders the output statically and writes it as HTML.  That way you could work with the widget view interactively, and when you have an output you want to share/persist, you could hit **Embed** and have the widget view HTML/JS replaced with a static view of the data at the point when you hit the button.

I don't have a great sense of how hard that would be with the current state of the widget system, but it seems like it should work conceptually?

**Comment by blink1073** [comment]
See #27.

**Comment by TimShawver** [comment]
PR has been merged to master.
