### ISSUE TITLE
How to make a link clickable / apply a custom formatter

### ISSUE THREAD

**Issue by janmechtel** [quantopian/qgrid#30]
I'm trying to make a cell clickable the value is http://link.com this question explains how to do it for slickgrid: http://stackoverflow.com/questions/9840548/how-to-put-html-into-slickgrid-cell

Any pointers how this would work with qgrid / ipython?

Thanks

**Comment by TimShawver** [comment]
You can set SlickGrid's grid options https://github.com/mleibman/SlickGrid/wiki/Grid-Options via the `show_grid` method.  You might be able to define your formatter function in a cell using a javascript cell magic (i.e. `%%javascript`) and then set it as the defaultFormatter option for all your grids like this: `qgrid.set_grid_option('defaultFormatter', 'myFormatterFunction'`.  I honestly haven't tried using a cell magic to customize the grid so I'm not sure if it would work.  Let me know if you get it working though because that would be pretty cool.

**Comment by janmechtel** [comment]
Great thanks!

**Comment by dwwkelly** [comment]
Any more details on how make this work?

**Comment by andyreagan** [comment]
It seems to "just work" for me.

I added a column to my dataframe like

    df["link_col"] = "<a href=\"http://google.com\" target=\"_blank\">test link</a>"

and  it works!
