### ISSUE TITLE
grid supports dynamic cells?

### ISSUE THREAD

**Issue by denfromufa** [quantopian/qgrid#34]
https://groups.google.com/forum/#!topic/jupyter/5wt3xTVaWIc

**Comment by TimShawver** [comment]
We now support updating the data that a grid is bound to without re-rendering the whole grid.  Here's the pull request that has a nice gif showing this: https://github.com/quantopian/qgrid/pull/49

Hopefully this helps.  Not sure I understood the question though, since the link is to an entire thread.
