### ISSUE TITLE
How does qgrid tell ipython notebook which js files to load?

### ISSUE THREAD

**Issue by djchou** [quantopian/qgrid#42]
Sorry, i'm pretty new to javascript.  How does qgrid tell ipython notebook which js files to load?  

The only place i could find any kind of "import" statement was in the slickgrid.js.template file:
var path_dictionary = {{
    jquery_drag: "{cdn_base_url}/lib/jquery.event.drag-2.2",
    slick_core: "{cdn_base_url}/lib/slick.core.2.2",
    slick_data_view: "{cdn_base_url}/lib/slick.dataview.2.2",
    slick_check_box_column: "{cdn_base_url}/lib/slick.checkboxselectcolumn",
    slick_row_selection_model: "{cdn_base_url}/lib/slick.rowselectionmodel",
    slick_grid: "{cdn_base_url}/lib/slick.grid.2.2",
    data_grid: "{cdn_base_url}/qgrid",
    data_grid_bb: "{cdn_base_url}/qgrid.bb",
    date_filter: "{cdn_base_url}/qgrid.datefilter",
    slider_filter: "{cdn_base_url}/qgrid.sliderfilter",
    text_filter: "{cdn_base_url}/qgrid.textfilter",
    filter_base:  "{cdn_base_url}/qgrid.filterbase",
    handlebars: "https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/2.0.0/handlebars.min"
}};

however, if i add a js file to this path, it does not appear to load in the browser.  Is there something else that needs to be modified for a JS file to load?

**Comment by TimShawver** [comment]
First thing I would do is make sure you're follow the steps in the [Running from Source] (https://github.com/quantopian/qgrid#running-from-source) section of the github page.  

The last step in that section mentions an nbinstall step which is relevant here.  Calling `nbinstall` copies the contents of the `qgridjs` folder to a special folder where jupyter notebook looks for it's extensions' javascript dependencies.

So in order to load an additional js file you would have to add it to the `qgridjs` folder, and then call `nbinstall` to copy the contents of that folder to the special folder that jupyter notebook looks in for the javascript. 

Additionally you would need to make the change that you're already attempting to make (i.e. adding to the slickgrid.js.template file).

Finally whenever you're doing frontend development you want to be aware of browser caching.  Chrome's dev tools have an option for turning off caching while the dev tools are open, so I'd suggest doing something like that while working on this.
