### ISSUE TITLE
Tables fail to render externally

### ISSUE THREAD

**Issue by dhimmel** [quantopian/qgrid#50]
I would like my `qgrid` tables to render on nbviewer.

I reran `qgrid_demo.ipynb` and the tables in the [resulting notebook did not show up in nbviewer](http://nbviewer.ipython.org/github/dhimmel/qgrid/blob/478053c4540e985be06663ecf210b7423a8da4cf/qgrid_demo.ipynb).

[Here are the details](https://github.com/quantopian/qgrid/files/64678/package-list.txt) of my installed packages.

**Comment by ssanderson** [comment]
@adzuci I think this is related to the CDN http/https issue you and @a-campbell hit with the CDN URL serving http instead of https.  Did you guys get a reliable local fix for that?

**Comment by TimShawver** [comment]
@dhimmel sorry this is super old but if you're still interested in getting this working, you might take a look at my comment on another issue: https://github.com/quantopian/qgrid/issues/53#issuecomment-192752791

If you follow steps 1-4 in that comment using the latest version of qgrid (0.3.1), then try rendering with nbviewer again you should see the grid.  For the [demo notebook] (http://nbviewer.jupyter.org/gist/TimShawver/b4bc80d1128407c56c9a) I used a gist while getting the notebook working, it was just easier than committing to a repository every time I wanted to test a change. 

Sorry the process is not well documented, I didn't realize it would be useful to people.

**Comment by TimShawver** [comment]
Please see my comment [here ](https://github.com/quantopian/qgrid/issues/110#issuecomment-336929573) explaining the situation with static exporting in qgrid 1.0.  TLDR; it doesn't work yet due to an issue with ipywidgets, but binder is a new option that you have available, which might be better for you anyways.

I'm going to close this because it's old and I'm hoping people will be able to get along with using binder instead of nbviewer.
