### ISSUE TITLE
Tables selectively not rendering

### ISSUE THREAD

**Issue by bicubic** [quantopian/qgrid#51]
Howdy, 
I have a notebook where the following correctly displays a table:
```
df = pd.DataFrame([1,2,3,4])
qgrid.show_grid(df)
```
However, when I try to display a denser dataframe in the same notebook, the output shows, but is removed on page refresh, while the above continues to display correctly. Is there some sort of limit to how big the dataframe can be? Any other potential cause for this? I can't release the dataset that's causing this. Some ideas for possible causes would be great so I can make a reproducible case. 

Edit: was able to repro the issue by repeatedly displaying a dataframe with of dimensions around 15x100. 3 times seems to do the trick to cause failure.
Seems like it was dataframe size related after all:
```
WrappedError {stack: "Error: Could not call widget save state callback.↵…in.js?v=40e10638fcf65fc1c057bff31d165e9d:12785:33", message: "Could not call widget save state callback.", error_stack: Array[2]}
error_stack: Array[2]
0: DOMException: Failed to set the 'widgets:http://192.168.1.113:8888/notebooks/qqgrid%20test.ipynb' property on 'Storage': Setting the value of 'widgets:http://192.168.1.113:8888/notebooks/qqgrid%20test.ipynb' exceeded the quota. at Error (native) at null.<anonymous> (http://192.168.1.113:8888/nbextensions/widgets/widgets/js/manager.js?v=20151223164406:523:27) at http://192.168.1.113:8888/nbextensions/widgets/widgets/js/manager.js?v=20151223164406:454:35
code: 22
message: "Failed to set the 'widgets:http://192.168.1.113:8888/notebooks/qqgrid%20test.ipynb' property on 'Storage': Setting the value of 'widgets:http://192.168.1.113:8888/notebooks/qqgrid%20test.ipynb' exceeded the quota."
name: "QuotaExceededError"
stack: "Error: Failed to set the 'widgets:http://192.168.1.113:8888/notebooks/qqgrid%20test.ipynb' property on 'Storage': Setting the value of 'widgets:http://192.168.1.113:8888/notebooks/qqgrid%20test.ipynb' exceeded the quota.↵    at Error (native)↵    at null.<anonymous> (http://192.168.1.113:8888/nbextensions/widgets/widgets/js/manager.js?v=20151223164406:523:27)↵    at http://192.168.1.113:8888/nbextensions/widgets/widgets/js/manager.js?v=20151223164406:454:35"
```

**Comment by TimShawver** [comment]
Hmm @bicubic there are limits to the size of the dataframe, but you should be running into issues at hundreds of thousands of rows, not just hundreds of rows.  

I think what's happening here is the widget is attempting to save it's state to Chrome's local storage or something when you refresh the page.  That's pretty surprising to me, I had no idea that sort of thing would happen on a page refresh.  That could mean your Chrome settings for local storage are set to something very low. 

This will need more investigation to really get to the bottom of what went wrong.  I'm going to close this for now because I think it's an environment specific issue.  Thanks for filling the issue and please let me know if you have any new information that would shed light on this (I know this was a while ago).
