### ISSUE TITLE
Possible to copy data?

### ISSUE THREAD

**Issue by klonuo** [quantopian/qgrid#7]
Hi,
thanks for this great extension!

I was wondering if copying data from qgrid table is possible, and if so how?

In Chrome, if I try to select some table cells it simple has no effect.
In Firefox, I'm able to select cells while dragging the mouse with left mouse button being pressed, but as soon as I release the left mouse button, selection disappears, and I'm not able to copy any data.

**Comment by lkursell** [comment]
Would it be possible to return a dataframe of the filtered table?

**Comment by TimShawver** [comment]
@lkursell getting the dataframe of the filtered table is now possible with the new qgrid 1.0 beta. Please see the following comment for more info: https://github.com/quantopian/qgrid/issues/87#issuecomment-336957973

**Comment by TimShawver** [comment]
I've added a `get_changed_df` method in qgrid 1.0 which should allow you to get a filtered copy of your DataFrame.  It will also reflect any sorts that have been applied, as well as edits to your cells.

See the installation instructions for the new qgrid 1.0 beta here: https://github.com/quantopian/qgrid#installation.  

Also here's the documentation for the `get_changed_df` method: http://qgrid.readthedocs.io/en/latest/#qgrid.QgridWidget.get_changed_df

Basically you'll create a QgridWidget instance (either directly or by calling show_grid), and then call `get_changed_df` on that instance.  Something like this:
```
# step 1 - first create the grid
qgrid_widget = qgrid.show_grid(df)

# step 2 - make your filtering/sorting changes and cell edits

# step 3 - in a new cell, get your changed DataFrame back
qgrid_widget.get_changed_df()
```
If you want to get this DataFrame in csv form, you can do that by calling `to_csv` on the DataFrame instance, and then copying the text that gets printed out. One caveat to be aware of is `to_csv` will likely crash your browser for very large DataFrames, so you'll probably want to specify a file path for `to_csv`, so that it's output goes directly to a file rather than to the browser.
