### ISSUE TITLE
Add logic for automatic display in ipython

### ISSUE THREAD

**Issue by ellisonbg** [quantopian/qgrid#8]
Using the IPython display architecture you can register functions that are automatically called when a `DataFrame` is displayed. This will enable users to optionally enable `qgrid` to display `DataFrame` by default, without an extra call. Running on a plane now, but please ping the ipython devs (or me later) on how this can be done. Awesome work!

**Comment by ellisonbg** [comment]
Here is the code that can do this:

https://gist.github.com/ellisonbg/5c54f995bfcd64b90dc2

**Comment by ellisonbg** [comment]
ping @aggFTW

**Comment by ssanderson** [comment]
@ellisonbg do you have thoughts on what a reasonable API for enabling this would be?

Presumably it'd be something like:

```
from qgrid import autouse

# Internally sets a display formatter for DataFrame and/or Series
autouse()
```

where the signature of autouse would be something like:

```
def autouse(autouse_dataframe=True, autouse_series=<what should this be?>):
```

**Comment by ssanderson** [comment]
(The other option would be to enable this by default as an import-time side effect, but that feels too aggressive.)

**Comment by TimShawver** [comment]
Finally got some time to do some dev work on qgrid and I included the automatic display capability in the new qgrid 1.0 beta.  There are two new methods `enable` and `disable`.  Here are the docs for these functions: http://qgrid.readthedocs.io/en/latest/#qgrid.enable

I don't think I'll have to add a `set_limit` function anymore because I ended up implementing "virtual scrolling" so that we only send 200 or so rows down to the browser at a time (which means qgrid can render very large DataFrames now). 

See the installation instructions on the [readme](https://github.com/quantopian/qgrid#installation)  if you'd like to try out the new beta.
