### ISSUE TITLE
Horizontal scrollbar not displayed when number of rows is too small

### ISSUE THREAD

**Issue by elanmart** [quantopian/qgrid#90]
Hi,

if the dataframe has too few rows to trigger vertical scrollbar, horizontal scrollbar will not be displayed either.

![screenshot from 2016-09-21 15-21-51](https://cloud.githubusercontent.com/assets/10772830/18712563/54559080-800f-11e6-9f71-8999c41a1fad.png)

**Comment by gnilrets** [comment]
Having this issue too.  Any workarounds?

**Comment by TimShawver** [comment]
This is fixed in the new qgrid 1.0 beta.  See the installation instructions on the [updated readme page](https://github.com/quantopian/qgrid#installation) to try it out.

I just tried it out and it seems to be working now:
![screen shot 2017-10-16 at 3 03 07 pm](https://user-images.githubusercontent.com/5055866/31630032-5a122d60-b283-11e7-9314-42058c54a680.png)
